#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
This script executes the PortSweep functions to sweep a set of ip address
and ports for possible WBEM Servers.

This is a demo version of the code until it is integrated into a single
multi-level script.

NOTE: This script must be executed in admin mode because python does not
allow the port inspect test in user mode.

"""
from __future__ import absolute_import

import sys
import os
from smipyping import create_sweep_argparser, parse_sweep_args, \
                      sweep_servers, TargetsData
from smipyping import DB_TYPE

def main(prog_name):
    """
        Port sweep demo program
    """
    argparser = create_sweep_argparser(prog_name)
    args = parse_sweep_args(argparser)

    provider_data = None
    if args.config_file is not None:
        provider_data = TargetsData.factory(args.config_file, DB_TYPE,
                                            args.verbose)
    else:
        provider_data = None

    # Sweep the servers and display result
    print('Start sweep for subnets %s, port %s, range %s:%s' %
          (args.subnet, args.port, args.min_octet_val, args.max_octet_val))
    print('This may take several minutes')
    sweep_servers(args.subnet, args.min_octet_val, args.max_octet_val,
                  args.port, args.no_threads, provider_data, args.verbose)

if __name__ == '__main__':
    sys.exit(main(os.path.basename(sys.argv[0])))
