#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
    Provides script interface to manage user data. This is temporary
    

    This script:
        Has a number of subcommands to manage the userdata.
"""
from __future__ import absolute_import

import sys as _sys
import os
from smipyping import ProcessTargetDataCli

def main(prog):
    """ Main function uses userdata.py to execute. This provides
        the parsing, connection and calls the test-server function

        Returns with either exit code = 0 if OK or exit_code = 1 if error
    """
    ProcessTargetDataCli(prog)

if __name__ == '__main__':
    prog_name = os.path.basename(_sys.argv[0])
    _sys.exit(main(prog_name))
